"""Initial Migration

Revision ID: 0c7fbe465e03
Revises: 
Create Date: 2017-11-08 09:39:23.676525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7fbe465e03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_code', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('abrv', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('fullname', sa.String(length=60), nullable=True),
    sa.Column('user_pwd', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_fullname'), 'users', ['fullname'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('constituencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('constituency_code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('county_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['county_code'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('governors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('othernames', sa.String(length=256), nullable=True),
    sa.Column('county_code', sa.Integer(), nullable=True),
    sa.Column('party_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['county_code'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['party_code'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('senators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('othernames', sa.String(length=256), nullable=True),
    sa.Column('county_code', sa.Integer(), nullable=True),
    sa.Column('party_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['county_code'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['party_code'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('womenreps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('othernames', sa.String(length=256), nullable=True),
    sa.Column('county_code', sa.Integer(), nullable=True),
    sa.Column('party_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['county_code'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['party_code'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deputygovernors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('othernames', sa.String(length=256), nullable=True),
    sa.Column('county_code', sa.Integer(), nullable=True),
    sa.Column('party_code', sa.Integer(), nullable=True),
    sa.Column('governor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['county_code'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['governor_id'], ['governors.id'], ),
    sa.ForeignKeyConstraint(['party_code'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('othernames', sa.String(length=256), nullable=True),
    sa.Column('constituency_code', sa.Integer(), nullable=True),
    sa.Column('county_code', sa.Integer(), nullable=True),
    sa.Column('party_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constituency_code'], ['constituencies.id'], ),
    sa.ForeignKeyConstraint(['county_code'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['party_code'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcas')
    op.drop_table('deputygovernors')
    op.drop_table('womenreps')
    op.drop_table('senators')
    op.drop_table('governors')
    op.drop_table('constituencies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_fullname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('parties')
    op.drop_table('counties')
    # ### end Alembic commands ###
