"""Migrations

Revision ID: 1f8cef06a760
Revises: 
Create Date: 2017-11-09 12:21:08.523312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8cef06a760'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constituencies', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'constituencies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'constituencies', type_='foreignkey')
    op.drop_column('constituencies', 'user_id')
    # ### end Alembic commands ###
