"""update all models

Revision ID: 821b325625ed
Revises: 63ce06f97aee
Create Date: 2017-11-08 15:43:43.016250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821b325625ed'
down_revision = '63ce06f97aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('constituencies_user_id_fkey', 'constituencies', type_='foreignkey')
    op.drop_column('constituencies', 'user_id')
    op.drop_constraint('counties_user_id_fkey', 'counties', type_='foreignkey')
    op.drop_column('counties', 'user_id')
    op.drop_constraint('deputygovernors_user_id_fkey', 'deputygovernors', type_='foreignkey')
    op.drop_column('deputygovernors', 'user_id')
    op.drop_constraint('governors_user_id_fkey', 'governors', type_='foreignkey')
    op.drop_column('governors', 'user_id')
    op.drop_constraint('mcas_user_id_fkey', 'mcas', type_='foreignkey')
    op.drop_column('mcas', 'user_id')
    op.drop_constraint('parties_user_id_fkey', 'parties', type_='foreignkey')
    op.drop_column('parties', 'user_id')
    op.drop_constraint('senators_user_id_fkey', 'senators', type_='foreignkey')
    op.drop_column('senators', 'user_id')
    op.drop_constraint('womenreps_user_id_fkey', 'womenreps', type_='foreignkey')
    op.drop_column('womenreps', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('womenreps', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('womenreps_user_id_fkey', 'womenreps', 'users', ['user_id'], ['id'])
    op.add_column('senators', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('senators_user_id_fkey', 'senators', 'users', ['user_id'], ['id'])
    op.add_column('parties', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('parties_user_id_fkey', 'parties', 'users', ['user_id'], ['id'])
    op.add_column('mcas', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('mcas_user_id_fkey', 'mcas', 'users', ['user_id'], ['id'])
    op.add_column('governors', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('governors_user_id_fkey', 'governors', 'users', ['user_id'], ['id'])
    op.add_column('deputygovernors', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('deputygovernors_user_id_fkey', 'deputygovernors', 'users', ['user_id'], ['id'])
    op.add_column('counties', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('counties_user_id_fkey', 'counties', 'users', ['user_id'], ['id'])
    op.add_column('constituencies', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('constituencies_user_id_fkey', 'constituencies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
