"""update mcas

Revision ID: b68e01858229
Revises: 2a6707ff5a04
Create Date: 2017-11-07 18:59:15.171368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68e01858229'
down_revision = '2a6707ff5a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('othernames', sa.String(length=256), nullable=True),
    sa.Column('constituency_code', sa.Integer(), nullable=True),
    sa.Column('county_code', sa.Integer(), nullable=True),
    sa.Column('party_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constituency_code'], ['constituencies.id'], ),
    sa.ForeignKeyConstraint(['county_code'], ['counties.id'], ),
    sa.ForeignKeyConstraint(['party_code'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('MCA')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MCA',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"MCA_id_seq"\'::regclass)'), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('othernames', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('constituency_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('county_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('party_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['constituency_code'], ['constituencies.id'], name='MCA_constituency_code_fkey'),
    sa.ForeignKeyConstraint(['county_code'], ['counties.id'], name='MCA_county_code_fkey'),
    sa.ForeignKeyConstraint(['party_code'], ['parties.id'], name='MCA_party_code_fkey'),
    sa.PrimaryKeyConstraint('id', name='MCA_pkey')
    )
    op.drop_table('mcas')
    # ### end Alembic commands ###
